-- User Creation & Grants --

CREATE USER foo WITH PASSWORD 'bar';

GRANT SELECT, INSERT, UPDATE, DELETE 
ON ALL TABLES IN SCHEMA public TO foo;

GRANT ALL PRIVILEGES 
ON ALL SEQUENCES IN SCHEMA public TO foo;

GRANT EXECUTE 
ON ALL FUNCTIONS IN SCHEMA public TO foo;
